// try-catch is used for handling errors in JavaScript.

try {
    let result = 5 / 0;
    console.log(result);
  } catch (error) {
    console.log("An error occurred: " + error);
  }